server:
   port: 9001
spring:
   application:
      name: DEPARTMENT-SERVICE
   datasource:
      url: jdbc:mysql://localhost:3306/departmentsDB?useSSL=false
      username: root
      password: root
   jpa:
      hibernate:
         use-new-id-generator-mappings: false
         ddl-auto: update
      properties:
         hibernate:
            dialet: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost