server:
   port: 9002
spring:
   application:
      name: USER-SERVICE
   datasource:
      url: jdbc:mysql://localhost:3306/usersDB?useSSL=false
      username: root
      password: root
   jpa:
      hibernate:
         use-new-id-generator-mappings: false
         ddl-auto: update
      properties:
         hibernate:
            dialet: org.hibernate.dialect.MySQL5InnoDBDialect
   zipkin:
      base-url: http://127.0.0.1:9411/